services:
  web:
    build:
      context: .
      target: final 
    ports:
      - 8080:80
    environment:
      - ConnectionString=Server=db;Initial Catalog=RoH;User Id=sa;Password=Pass@word;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
